################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Data/CodeX/Firmware/Appli/Core/Src/app.c \
D:/Data/CodeX/Firmware/Appli/Core/Src/app_bqueue.c \
D:/Data/CodeX/Firmware/Appli/Core/Src/app_camera.c \
D:/Data/CodeX/Firmware/Appli/Core/Src/app_cpuload.c \
D:/Data/CodeX/Firmware/Appli/Core/Src/app_lcd.c \
D:/Data/CodeX/Firmware/Appli/Core/Src/app_postprocess.c \
D:/Data/CodeX/Firmware/Appli/Core/Src/app_rgb_led.c \
D:/Data/CodeX/Firmware/Appli/Core/Src/main.c \
D:/Data/CodeX/Firmware/Appli/Core/Src/secure_nsc.c \
D:/Data/CodeX/Firmware/Appli/Core/Src/stm32_lcd_ex.c \
D:/Data/CodeX/Firmware/Appli/Core/Src/stm32n6xx_hal_msp.c \
D:/Data/CodeX/Firmware/Appli/Core/Src/stm32n6xx_hal_timebase_threadx.c \
D:/Data/CodeX/Firmware/Appli/Core/Src/stm32n6xx_it.c \
../Application/User/Core/syscalls.c \
../Application/User/Core/sysmem.c 

OBJS += \
./Application/User/Core/app.o \
./Application/User/Core/app_bqueue.o \
./Application/User/Core/app_camera.o \
./Application/User/Core/app_cpuload.o \
./Application/User/Core/app_lcd.o \
./Application/User/Core/app_postprocess.o \
./Application/User/Core/app_rgb_led.o \
./Application/User/Core/main.o \
./Application/User/Core/secure_nsc.o \
./Application/User/Core/stm32_lcd_ex.o \
./Application/User/Core/stm32n6xx_hal_msp.o \
./Application/User/Core/stm32n6xx_hal_timebase_threadx.o \
./Application/User/Core/stm32n6xx_it.o \
./Application/User/Core/syscalls.o \
./Application/User/Core/sysmem.o 

C_DEPS += \
./Application/User/Core/app.d \
./Application/User/Core/app_bqueue.d \
./Application/User/Core/app_camera.d \
./Application/User/Core/app_cpuload.d \
./Application/User/Core/app_lcd.d \
./Application/User/Core/app_postprocess.d \
./Application/User/Core/app_rgb_led.d \
./Application/User/Core/main.d \
./Application/User/Core/secure_nsc.d \
./Application/User/Core/stm32_lcd_ex.d \
./Application/User/Core/stm32n6xx_hal_msp.d \
./Application/User/Core/stm32n6xx_hal_timebase_threadx.d \
./Application/User/Core/stm32n6xx_it.d \
./Application/User/Core/syscalls.d \
./Application/User/Core/sysmem.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/Core/app.o: D:/Data/CodeX/Firmware/Appli/Core/Src/app.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/app_bqueue.o: D:/Data/CodeX/Firmware/Appli/Core/Src/app_bqueue.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/app_camera.o: D:/Data/CodeX/Firmware/Appli/Core/Src/app_camera.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/app_cpuload.o: D:/Data/CodeX/Firmware/Appli/Core/Src/app_cpuload.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/app_lcd.o: D:/Data/CodeX/Firmware/Appli/Core/Src/app_lcd.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/app_postprocess.o: D:/Data/CodeX/Firmware/Appli/Core/Src/app_postprocess.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/app_rgb_led.o: D:/Data/CodeX/Firmware/Appli/Core/Src/app_rgb_led.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/main.o: D:/Data/CodeX/Firmware/Appli/Core/Src/main.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/secure_nsc.o: D:/Data/CodeX/Firmware/Appli/Core/Src/secure_nsc.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/stm32_lcd_ex.o: D:/Data/CodeX/Firmware/Appli/Core/Src/stm32_lcd_ex.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/stm32n6xx_hal_msp.o: D:/Data/CodeX/Firmware/Appli/Core/Src/stm32n6xx_hal_msp.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/stm32n6xx_hal_timebase_threadx.o: D:/Data/CodeX/Firmware/Appli/Core/Src/stm32n6xx_hal_timebase_threadx.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/stm32n6xx_it.o: D:/Data/CodeX/Firmware/Appli/Core/Src/stm32n6xx_it.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/%.o Application/User/Core/%.su Application/User/Core/%.cyclo: ../Application/User/Core/%.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Application-2f-User-2f-Core

clean-Application-2f-User-2f-Core:
	-$(RM) ./Application/User/Core/app.cyclo ./Application/User/Core/app.d ./Application/User/Core/app.o ./Application/User/Core/app.su ./Application/User/Core/app_bqueue.cyclo ./Application/User/Core/app_bqueue.d ./Application/User/Core/app_bqueue.o ./Application/User/Core/app_bqueue.su ./Application/User/Core/app_camera.cyclo ./Application/User/Core/app_camera.d ./Application/User/Core/app_camera.o ./Application/User/Core/app_camera.su ./Application/User/Core/app_cpuload.cyclo ./Application/User/Core/app_cpuload.d ./Application/User/Core/app_cpuload.o ./Application/User/Core/app_cpuload.su ./Application/User/Core/app_lcd.cyclo ./Application/User/Core/app_lcd.d ./Application/User/Core/app_lcd.o ./Application/User/Core/app_lcd.su ./Application/User/Core/app_postprocess.cyclo ./Application/User/Core/app_postprocess.d ./Application/User/Core/app_postprocess.o ./Application/User/Core/app_postprocess.su ./Application/User/Core/app_rgb_led.cyclo ./Application/User/Core/app_rgb_led.d ./Application/User/Core/app_rgb_led.o ./Application/User/Core/app_rgb_led.su ./Application/User/Core/main.cyclo ./Application/User/Core/main.d ./Application/User/Core/main.o ./Application/User/Core/main.su ./Application/User/Core/secure_nsc.cyclo ./Application/User/Core/secure_nsc.d ./Application/User/Core/secure_nsc.o ./Application/User/Core/secure_nsc.su ./Application/User/Core/stm32_lcd_ex.cyclo ./Application/User/Core/stm32_lcd_ex.d ./Application/User/Core/stm32_lcd_ex.o ./Application/User/Core/stm32_lcd_ex.su ./Application/User/Core/stm32n6xx_hal_msp.cyclo ./Application/User/Core/stm32n6xx_hal_msp.d ./Application/User/Core/stm32n6xx_hal_msp.o ./Application/User/Core/stm32n6xx_hal_msp.su ./Application/User/Core/stm32n6xx_hal_timebase_threadx.cyclo ./Application/User/Core/stm32n6xx_hal_timebase_threadx.d ./Application/User/Core/stm32n6xx_hal_timebase_threadx.o ./Application/User/Core/stm32n6xx_hal_timebase_threadx.su ./Application/User/Core/stm32n6xx_it.cyclo ./Application/User/Core/stm32n6xx_it.d ./Application/User/Core/stm32n6xx_it.o ./Application/User/Core/stm32n6xx_it.su ./Application/User/Core/syscalls.cyclo ./Application/User/Core/syscalls.d ./Application/User/Core/syscalls.o ./Application/User/Core/syscalls.su ./Application/User/Core/sysmem.cyclo ./Application/User/Core/sysmem.d ./Application/User/Core/sysmem.o ./Application/User/Core/sysmem.su

.PHONY: clean-Application-2f-User-2f-Core

