################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash/norflash.c \
D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash/norflash_by25fq128el.c \
D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash/norflash_mx25um25645g.c \
D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash/norflash_xspi.c 

OBJS += \
./Drivers/BSP/NORFlash/norflash.o \
./Drivers/BSP/NORFlash/norflash_by25fq128el.o \
./Drivers/BSP/NORFlash/norflash_mx25um25645g.o \
./Drivers/BSP/NORFlash/norflash_xspi.o 

C_DEPS += \
./Drivers/BSP/NORFlash/norflash.d \
./Drivers/BSP/NORFlash/norflash_by25fq128el.d \
./Drivers/BSP/NORFlash/norflash_mx25um25645g.d \
./Drivers/BSP/NORFlash/norflash_xspi.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/BSP/NORFlash/norflash.o: D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash/norflash.c Drivers/BSP/NORFlash/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/NORFlash/norflash_by25fq128el.o: D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash/norflash_by25fq128el.c Drivers/BSP/NORFlash/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/NORFlash/norflash_mx25um25645g.o: D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash/norflash_mx25um25645g.c Drivers/BSP/NORFlash/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/NORFlash/norflash_xspi.o: D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash/norflash_xspi.c Drivers/BSP/NORFlash/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I"D:/Data/CodeX/Firmware/Drivers/BSP/NORFlash" -I"D:/Data/CodeX/Firmware/Drivers/BSP/HyperRAM" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LED" -I"D:/Data/CodeX/Firmware/Drivers/BSP/LCD" -I"D:/Data/CodeX/Firmware/Drivers/BSP/BUS" -I"D:/Data/CodeX/Firmware/Drivers/BSP/UART" -I"D:/Data/CodeX/Firmware/Drivers/CMSIS/DSP/Include" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/ports/cortex_m55/gnu/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/common/inc" -I"D:/Data/CodeX/Firmware/Middlewares/ThreadX/utility/execution_profile_kit" -I"D:/Data/CodeX/Firmware/Appli/ThreadX/App" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/isp/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_ISP/evision/Inc" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_ISP" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"D:/Data/CodeX/Firmware/Appli/STM32_MW_CAMERA" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Inc" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/ll_aton" -I"D:/Data/CodeX/Firmware/Middlewares/AI/Npu/Devices/STM32N6XX" -I"D:/Data/CodeX/Firmware/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"D:/Data/CodeX/Firmware/Utilities/lcd" -I"D:/Data/CodeX/Firmware/Model" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-BSP-2f-NORFlash

clean-Drivers-2f-BSP-2f-NORFlash:
	-$(RM) ./Drivers/BSP/NORFlash/norflash.cyclo ./Drivers/BSP/NORFlash/norflash.d ./Drivers/BSP/NORFlash/norflash.o ./Drivers/BSP/NORFlash/norflash.su ./Drivers/BSP/NORFlash/norflash_by25fq128el.cyclo ./Drivers/BSP/NORFlash/norflash_by25fq128el.d ./Drivers/BSP/NORFlash/norflash_by25fq128el.o ./Drivers/BSP/NORFlash/norflash_by25fq128el.su ./Drivers/BSP/NORFlash/norflash_mx25um25645g.cyclo ./Drivers/BSP/NORFlash/norflash_mx25um25645g.d ./Drivers/BSP/NORFlash/norflash_mx25um25645g.o ./Drivers/BSP/NORFlash/norflash_mx25um25645g.su ./Drivers/BSP/NORFlash/norflash_xspi.cyclo ./Drivers/BSP/NORFlash/norflash_xspi.d ./Drivers/BSP/NORFlash/norflash_xspi.o ./Drivers/BSP/NORFlash/norflash_xspi.su

.PHONY: clean-Drivers-2f-BSP-2f-NORFlash

